### ISSUE TITLE
issues with installation

### ISSUE THREAD

**Issue by wlchui** [dkumor/rtcbot#16] opened 2020-08-30 09:26 UTC
when i did a 

sudo pip3 install rtcbot, i have the following issue:

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting rtcbot
  Downloading https://files.pythonhosted.org/packages/18/b1/704e6195146d356af16ba8403bc8d9acb8a804335047ecc152662ffd666d/rtcbot-0.2.0-py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 1.0MB/s
Requirement already satisfied: pyserial in /usr/lib/python3/dist-packages (from rtcbot) (3.4)
Requirement already satisfied: aiohttp in /usr/lib/python3/dist-packages (from rtcbot) (3.5.1)
Collecting soundcard (from rtcbot)
Could not install packages due to an EnvironmentError: 403 Client Error: Forbidden for url: https://www.piwheels.org/simple/soundcard/

**Comment by RtjShreyD** [comment] 2020-08-30 10:00
Its an Environment Error nothing to do with the library, why don't you try installing it in a virtual environment.
Follow these steps:

Make a project dir: `mkdir rtc_proj`
Get into project dir: `cd rtc_proj`
Make a virtualenv: `python3 -m venv rtc_env`
Activate the env: `source retc_env/bin/activate`
Upgrade pip: `pip install -U pip`
Install rtcbot library: `pip install rtcbot`

It works flawlessly

**Comment by dkumor** [comment] 2020-08-30 15:32
Can you see what happens when you run `sudo pip3 install soundcard`? Looks like there might be some intermittent issue with the pypi servers or something.

**Comment by dkumor** [comment] 2020-09-03 06:46
The issue should now be fixed - the registry pip uses for Pi apparently just changed to be case-sensitive in package names, so the SoundCard dependency wasn't parsing. I have uploaded a new version to pypi that has the correct casing.

Please reopen if it still doesn't install!

**Comment by dkumor** [comment] 2020-09-03 15:38
Apparently the fix didn't work

**Comment by dkumor** [comment] 2020-09-03 15:43
For now, the best alternative is to download the wheel manually from https://pypi.org/project/SoundCard/#files - so:
```
sudo pip3 install https://files.pythonhosted.org/packages/21/95/0c8574e84de4f2ee1c74ad0ae45af19a72b1296bba21837157efca46595a/SoundCard-0.4.0-py3-none-any.whl
sudo pip3 install rtcbot
```

I will try to contact the maintainers of piwheels to fix this problem.

**Comment by dkumor** [comment] 2020-09-03 17:09
The issue will be resolved once the fix is deployed at piwheels. In the mean time, please use the above manual install instructions.

**Comment by dkumor** [comment] 2020-09-10 17:25
I believe that the issue is fixed on piwheel's end now. Please reopen if you continue having problems!

**Closed by dkumor** 2020-09-10 17:25 UTC
